language: node_js
node_js: "stable"

before_install:
   - stty cols 80
cache:
  directories:
  - node_modules
dist: trusty
sudo: required

addons:
  firefox: latest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
script: npm run uitest